// OpenTelemetry naming constants only. Phase 1 intentionally does not bootstrap an SDK or exporter.
export const SPAN_NAMES = {
  HTTP_SERVER: (method: string, route: string): string => `${method} ${route}`,
  WS_RECEIVE: (channel: string): string => `WS RECEIVE ${channel}`,
  WS_SEND: (channel: string): string => `WS SEND ${channel}`,
  DB_TABLE: (operation: string, table: string): string => `${operation} ${table}`,
  DB_MULTI: (operation: string): string => `${operation} sqlite`,
  FEED_SUBSCRIBE: 'feed.subscribe',
  FEED_RECONNECT: 'feed.reconnect',
  FEED_FETCH: 'feed.fetch',
  FEED_PARSE_BATCH: 'feed.parse_batch',
  FEED_PERSIST_BATCH: 'feed.persist_batch',
  LLM_OPENROUTER_CHAT: 'llm.openrouter.chat',
  AGENT_DECISION: 'agent.decision',
} as const;

export const METRIC_NAMES = {
  HTTP_SERVER_REQUEST_DURATION: 'http.server.request.duration',
  HTTP_CLIENT_REQUEST_DURATION: 'http.client.request.duration',
  DB_CLIENT_OPERATION_DURATION: 'db.client.operation.duration',
  WS_MESSAGE_DURATION: 'app.ws.message.duration',
  AGENT_DECISION_DURATION: 'app.agent.decision.duration',
  WS_CONNECTION_COUNT: 'app.ws.connection.count',
  BOTTLENECK_QUEUE_COUNT: 'app.bottleneck.queue.count',
  FEED_SUBSCRIPTION_COUNT: 'app.feed.subscription.count',
  FEED_INGESTED_MESSAGES: 'app.feed.ingested.messages',
  WS_SENT_MESSAGES: 'app.ws.sent.messages',
  RETRY_FAILED_ATTEMPTS: 'app.retry.failed.attempts',
} as const;

export const ATTR_KEYS = {
  HTTP_REQUEST_METHOD: 'http.request.method',
  HTTP_ROUTE: 'http.route',
  HTTP_RESPONSE_STATUS_CODE: 'http.response.status_code',
  URL_PATH: 'url.path',
  URL_SCHEME: 'url.scheme',
  SERVER_ADDRESS: 'server.address',
  SERVER_PORT: 'server.port',
  NETWORK_PROTOCOL_VERSION: 'network.protocol.version',
  DB_SYSTEM_NAME: 'db.system.name',
  DB_NAMESPACE: 'db.namespace',
  DB_OPERATION_NAME: 'db.operation.name',
  DB_COLLECTION_NAME: 'db.collection.name',
  DB_SYSTEM_SQLITE: 'sqlite',
  APP_FEED_SOURCE: 'app.feed.source',
  APP_MARKET_SYMBOL: 'app.market.symbol',
  APP_STRATEGY_NAME: 'app.strategy.name',
  APP_MONEY_SCALE: 'app.money.scale',
  APP_AI_PROVIDER: 'app.ai.provider',
  APP_AI_MODEL: 'app.ai.model',
  RETRY_ATTEMPT: 'retry.attempt',
  RETRY_DELAY_MS: 'retry.delay_ms',
  UPSTREAM_STATUS_CODE: 'upstream.status_code',
  RATE_LIMITER_PROVIDER: 'rate_limiter.provider',
  RATE_LIMITER_QUEUED: 'rate_limiter.queued',
} as const;
